CREATE TABLE lotecsv (
    dia varchar(10),
    hora TIME,
    responsavel varchar(50),
    observacao varchar(500),
    prod_1_peso INT,
    prod_2_peso INT,
    prod_3_peso INT,
    prod_4_peso INT,
    prod_5_peso INT,
    prod_6_peso INT,
    prod_7_peso INT,
    prod_8_peso INT,
    prod_9_peso INT,
    prod_10_peso INT,
    prod_11_peso INT,
    prod_12_peso INT,
    prod_13_peso INT,
    prod_14_peso INT,
    prod_15_peso INT,
    prod_16_peso INT,
    prod_17_peso INT,
    prod_18_peso INT,
    prod_19_peso INT,
    prod_20_peso INT,
    prod_21_peso INT,
    prod_22_peso INT,
    prod_23_peso INT,
    prod_24_peso INT
);
use cadastro;
CREATE TABLE pesagemcsv (
    dia VARCHAR(10),
    hora TIME,
    responsavel VARCHAR(50),
    observacao VARCHAR(500),
    prod_1_peso INT,
    prod_2_peso INT,
    prod_3_peso INT,
    prod_4_peso INT,
    prod_5_peso INT,
    prod_6_peso INT,
    prod_7_peso INT,
    prod_8_peso INT,
    prod_9_peso INT,
    prod_10_peso INT,
    prod_11_peso INT,
    prod_12_peso INT,
    prod_13_peso INT,
    prod_14_peso INT,
    prod_15_peso INT,
    prod_16_peso INT,
    prod_17_peso INT,
    prod_18_peso INT,
    prod_19_peso INT,
    prod_20_peso INT,
    prod_21_peso INT,
    prod_22_peso INT,
    prod_23_peso INT,
    prod_24_peso INT,
    valida TINYINT(1)
);

select * from cadastro.pesagemcsv;
select * from lotecsv;
select * from nomearq;
